### ISSUE TITLE
right clic actions

### ISSUE THREAD

**Issue by feth** [mike-perdide/gitbuster#11]
I wish I could copy commits or delete them on a right clic. 
Or add a commit to the selection. Or add commits in the copy paste buffer before/after the commit I'm right clicking on.

**Comment by feth** [comment]
also : right click : create a new branch from here.

**Comment by mike-perdide** [comment]
The context menu with the copy, delete, copy after, copy before is implemented by : https://github.com/mike-perdide/gitbuster/commit/f80e6afc4c5515a1f8c1b4cda7c5266c85395e3a.

Adding a commit to the selection can be done by using Ctrl + Click.

**Comment by mike-perdide** [comment]
The "create new branch from commit" feature is done by : https://github.com/mike-perdide/gitbuster/commit/ef2616ba40b91399c9025350b5d2fbedf632736c.
