### ISSUE TITLE
Show commits about to be deleted

### ISSUE THREAD

**Issue by feth** [mike-perdide/gitbuster#14]
There must be a way for the user to figure out where he did something, like deleting commits.
I suggest keeping them in the branch view, but in italics and strikethrough.

**Comment by mike-perdide** [comment]
This feature is done by : https://github.com/mike-perdide/gitbuster/commit/57d224e6c180ffe9c780d6f8b3da60205c69354d and https://github.com/mike-perdide/gfbi_core/commit/9bb4e1458e5448c18e3483ee261ac0459bd1f655
