### ISSUE TITLE
Recent/favorite repositories

### ISSUE THREAD

**Issue by feth** [mike-perdide/gitbuster#15]
this would make the UI sexy : when starting gitbuster, I would like to be presented with a dialog that remembers the repositories I usely work on, just like chromium does with my most visited sites.

**Comment by mike-perdide** [comment]
UI is now sexy : https://github.com/mike-perdide/gitbuster/commit/08f1144d46bcaabf054c06748e360c553f3c48b2 and https://github.com/mike-perdide/gitbuster/commit/15ba79df7f04e349601d28d7ecf1c751d280c15d.
