### ISSUE TITLE
Git repo should be left clean after leaving gitbuster

### ISSUE THREAD

**Issue by tonthon** [mike-perdide/gitbuster#18]
No tmp_rebase should be left when getting out

**Comment by mike-perdide** [comment]
This is done by : https://github.com/mike-perdide/gfbi_core/commit/04c048d407e977dae24c0571c0f640664e4c96f8. For cleanup after interrupting the rebase thread, see : https://github.com/mike-perdide/gitbuster/issues/17.

**Comment by tonthon** [comment]
Using our specific problematic git repo :

```
open gitbuster
go to the rebase thumb
choose the refactor-profile branch
duplicate "Fichier rajouté"(line 7) under himself (line 8)
Apply
Apply doesn't end so we quit
go to the git repo, you're under the tmp_rebase branch
```

**Comment by mike-perdide** [comment]
The freezing bug still exists in gfbi_core, but gitbuster is doing proper cleanup as of f9cf5f0be70b7eb57686.
