### ISSUE TITLE
pip installation doesn't work

### ISSUE THREAD

**Issue by rcfox** [mike-perdide/gitbuster#62]
$ pip install gitbuster
Unknown or unsupported command 'install'

I'm not really sure of why you'd use pip with a Python project either.

**Comment by mike-perdide** [comment]
Maybe we're not talking about the same pip command. I'm thinking about http://guide.python-distribute.org/pip.html. The manpage of pip says:

```
 NAME
     pip - install Python packages
```

**Comment by rcfox** [comment]
Ah, the pip I have is http://search.cpan.org/perldoc?pip

NAME
       pip - The Perl Installation Program, for scripted and third-party distribution installation.

**Comment by mike-perdide** [comment]
Well I don't know who named his project last, but that's unfortunate. Thanks for pointing that out. I added a warning message in the README file.
d4ece165a474b30bf923
